# Generated by Django 3.1.2 on 2021-01-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium_crawler.searchquery')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('article_link', models.TextField()),
                ('article_image', models.TextField()),
                ('article_readtime', models.CharField(max_length=50)),
                ('article_publish_on', models.CharField(max_length=30)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium_crawler.searchquery')),
            ],
        ),
    ]
