# Generated by Django 3.1.2 on 2021-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='articles_count',
            field=models.IntegerField(default=10),
        ),
    ]
