# Generated by Django 3.1.2 on 2021-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_crawler', '0002_searchquery_articles_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_link',
            field=models.TextField(null=True),
        ),
    ]
