# Generated by Django 3.1.2 on 2021-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_crawler', '0003_tags_tag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='responses',
            field=models.CharField(default='0 responses', max_length=50),
        ),
    ]
